### ISSUE TITLE
Define SoilWise metadata profile

### ISSUE THREAD

**Issue by DajanaSnopkova** [soilwise-he/metadata-validator#1]
Definition of metadata profile, that will be used for core validation, that will be applied to all harvested metadata resources. A combination of INSPIRE and DublinCore is under consideration.

- [x] Find out what was used for EJPSoil

Links to [Prepare ETS config for core  metadata validation](https://github.com/soilwise-he/metadata-validator/issues/3), it needs to be agreed, for what purpose the results of this core validation will be used (e.g. displaying and findability of the metadata resource, ranking in search results...)

**Comment by pvgenuchten** [comment]
see also:

- https://github.com/soilwise-he/soilwise-ontology/issues/5
- https://github.com/soilwise-he/soilwise-ontology/issues/3

issue 3 above has the ejpsoil profile extended with some new issues

**Comment by DajanaSnopkova** [comment]
SoilWise metadata profile is defined as EJPSoil metadata profile extended by few record as defined by the ESDAC WG in the following Excel.
[EUSO Data WG metadata template-final-proposal (2).xlsx](https://github.com/user-attachments/files/16158768/EUSO.Data.WG.metadata.template-final-proposal.2.xlsx)

**Comment by pvgenuchten** [comment]
Note that EJPSoil is much too extended to act as core model (notice that #16 states that records which do not validate the core profile, are rejected from the catalogue), suggestion for minimal is: 

- identifier
- title
- date
- contact point
- source catalogue

what do you think @DajanaSnopkova
