### ISSUE TITLE
Prepare ETS config for INSPIRE metadata validation

### ISSUE THREAD

**Issue by DajanaSnopkova** [soilwise-he/metadata-validator#4]
DoD:
- profile is available for validation in admin Hale console

**Comment by BerkvensNick** [comment]
not in first iteration

**Comment by thorsten-reitz** [comment]
Yes, the integrated metadata validation in hale components is built on the current ETF/INSPIRE validator. However, if metadata is managed outside of hale, it will only work out of the box for dataset metadata. For service metadata, we could still use the deployed ETF programmatically, but some external service metadata management system would have to trigger the validation.

**Comment by DajanaSnopkova** [comment]
Thanks for the info; however, I have trouble understanding what you mean by: "it will only work out of the box for dataset metadata". Can you clarify?

**Comment by pvgenuchten** [comment]
I think @thorsten-reitz means that this functionality is available in hale connect for datasets being described as inspire iso19139:2007, which is a known limitation, so closing this
